[workspace]
name = "test_project"
version = "0.1.0"
preview = ["pixi-build"]
authors = ["Pradyot Ranjan <99216956+pradyotRanjan@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[dependencies]
# rust = ">=1.90,<1.97"
pkg-config = ">=0.29"
# clang = ">=16,<19"

ffmpeg = ">=7,<8"
opencv = ">=4.9,<4.11"
libwebp = ">=1.3,<1.5"

[feature.mpv.dependencies]
mpv = ">=0.34,<0.36"

[tasks]
build = { description = "Build the test_project using cargo", cmd = "cargo build" }
run   = { description = "Run the test_project",               cmd = "cargo run" }
test  = { description = "Run cargo test",                     cmd = "cargo test" }
check = { description = "Fast check using cargo check",        cmd = "cargo check" }
